#!/bin/bash
while [[ true ]]; do

cat ani1.txt #start

sleep 0.5
clear

cat ani2.txt #hrumhrum

sleep 0.2
clear

cat ani3.txt #occhiolino

sleep 0.2
clear

cat ani4.txt #zampa1 su

sleep 0.2
clear

cat ani5.txt #zampa2 su

sleep 0.4
clear

cat ani6.txt #alza 1

sleep 0.2
clear

cat ani7.txt #alza 2

sleep 0.5
clear

cat ani6.txt #abassa 1

sleep 0.2
clear

cat ani5.txt #abassa 2

sleep 0.4
clear

cat ani4.txt #zampa1

sleep 0.4
clear

cat ani8.txt #fine

sleep 0.5
clear

done
